# Generated by Django 5.2.7 on 2025-11-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stud_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
